name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: main.tex
      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: cv.pdf
          path: main.pdf
      - name: Commit and push compiled pdf
        uses: EndBug/add-and-commit@v4
        with:
          add: main.pdf
          author_name: CI pipeline
          message: auto-compile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
